//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datebase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datebase.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event number 1..
        /// </summary>
        internal static string EVENT_1 {
            get {
                return ResourceManager.GetString("EVENT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event number 10..
        /// </summary>
        internal static string EVENT_10 {
            get {
                return ResourceManager.GetString("EVENT_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event number 2..
        /// </summary>
        internal static string EVENT_2 {
            get {
                return ResourceManager.GetString("EVENT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event number 3..
        /// </summary>
        internal static string EVENT_3 {
            get {
                return ResourceManager.GetString("EVENT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event number 4..
        /// </summary>
        internal static string EVENT_4 {
            get {
                return ResourceManager.GetString("EVENT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event number 5..
        /// </summary>
        internal static string EVENT_5 {
            get {
                return ResourceManager.GetString("EVENT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event number 6..
        /// </summary>
        internal static string EVENT_6 {
            get {
                return ResourceManager.GetString("EVENT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event number 7..
        /// </summary>
        internal static string EVENT_7 {
            get {
                return ResourceManager.GetString("EVENT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event number 8..
        /// </summary>
        internal static string EVENT_8 {
            get {
                return ResourceManager.GetString("EVENT_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event number 9..
        /// </summary>
        internal static string EVENT_9 {
            get {
                return ResourceManager.GetString("EVENT_9", resourceCulture);
            }
        }
    }
}
